-- This file can be required during runtime, so we need conditional definitions here
omni = omni or { lib = omni and omni.lib or {} }
local omnimod_data = helpers.stage == "prototype" and data.raw["mod-data"].omnimods.data or prototypes.mod_data.omnimods.data

--- Adds the given data table to mod-data, preserving existing values if an override isn't given
--[[@param info_table { 
        base: string?,
        compressed: string?,
        compact: string?,
        nanite: string?,
        quantum: string?,
        singularity: string?
    } the correlated recipe data to add ]]
---@param key "compressed-recipes"|string the data table to add the data to, default "compressed_recipes"
function omni.lib.add_to_mod_data(info_table, key)
    key = key or "compressed_recipes" -- default to the recipe table
    local mod_data = omnimod_data[key]
    log("Adding: " .. serpent.line(info_table))
    -- pointers to the same table for other possible lookup names
    local existing_data = (info_table.base and mod_data[info_table.base]) 
                        or (info_table.compressed and mod_data[info_table.compressed])
                        or info_table
    -- Merge in our new data (this would be unnecessary but we want to create the indexes for anything new)
    -- e.g. where 
    for k, v in pairs(info_table) do
        mod_data[v] = existing_data
        existing_data[k] = v
    end
end

--- Adds the compressed<->uncompressed recipe info to mod-data
---@param base_recipe_name       string uncompressed (base) recipe name
---@param compressed_recipe_name string compressed recipe name
function omni.lib.add_recipe_to_mod_data(base_recipe_name, compressed_recipe_name)
    local mod_data = omnimod_data.compressed_recipes
    -- pointers to the same table for other possible lookup names
    local existing_data = mod_data[base_recipe_name] or mod_data[compressed_recipe_name] or {}
    mod_data[base_recipe_name] = existing_data
    mod_data[compressed_recipe_name] = existing_data
    existing_data.base = base_recipe_name
    existing_data.compressed = compressed_recipe_name
end

--- Checks if the given recipe is generated by omnicompression et al
---@param compressed_recipe_name string the recipe to check
---@return boolean recipe_is_compressed whether the given recipe is compressed
function omni.lib.is_compressed_recipe(compressed_recipe_name)
    local meta = omnimod_data.compressed_recipes[compressed_recipe_name]
    if not meta then return false end
    return meta.base ~= compressed_recipe_name
end

--- Checks if the given building is compressed (as in tiered, not a compressed item)
--- Due to limitations™, this is by recipe name and not building name. I hope they're the same!
---@param compressed_building_name string the building to check
---@return boolean building_is_compressed whether the given building is compressed
function omni.lib.is_compressed_building(compressed_building_name)
    return not not omnimod_data.all_compressed_buildings[compressed_building_name]
end