omni.fluid.excempt_boiler("crystal-reactor")
omni.fluid.excempt_boiler("burner-turbine")
omni.fluid.excempt_boiler("burner-generator")
require("prototypes.sluids-generation")
--require("prototypes.sluids-from-fluids")
--require("prototypes.sluids-building-changes")
--require("prototypes.sluids-generation")
